title: SyncFiles Documentation
email: depp@zdome.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: https://depp.github.io
url: /syncfiles/
twitter_username: DietrichEpp
github_username:  depp

theme: just-the-docs
plugins:
  - jekyll-feed

exclude:
  - push.sh
